### ISSUE TITLE
colors not showing visually inspite of tokens being recognized

### ISSUE THREAD

**Issue by triptu** [nderscore/tamagui-typescript-plugin#2]
I'm most likely missing something obvious but can't seem to figure it out 😢. Is there any reason the tokens will be recognized but the colors not show visually?

![image](https://github.com/nderscore/tamagui-typescript-plugin/assets/16299282/ddbc3f63-51a4-4d15-893f-19d10f8da2a3)

**Comment by nderscore** [comment]
Most likely your documentation panel is hidden.

You can open it by pressing `ctrl+space`/`cmd+space` while one of the tokens is highlighted.

Alternatively, I think there should also be a `>` button on the far right if you hover with your mouse. That button will do the same thing.
