### ISSUE TITLE
Not getting the nice looking popup

### ISSUE THREAD

**Issue by 0xBigBoss** [nderscore/tamagui-typescript-plugin#8]
<img width="1915" alt="Screenshot 2024-01-05 at 22 04 15" src="https://github.com/nderscore/tamagui-typescript-plugin/assets/95193764/5649726b-c089-4081-8c75-aeb2c05f0636">

Tried turning on TS logging to see what's up and can't find a reason why the pop up isn't the nice preview I was expecting. 

You can see the project and how it's setup here, https://github.com/0xsend/sendapp.

Any ideas on what I was missing?

**Comment by nderscore** [comment]
Looks like it should be working.

Try pressing `cmd/ctrl`+`space` to open the suggestion details panel. 

Alternatively, there should be a `>` on the far right if you hover with the mouse.

**Comment by 0xBigBoss** [comment]
Aww ty. I had to click the `>`.

<img width="887" alt="Screenshot 2024-01-06 at 22 05 44" src="https://github.com/nderscore/tamagui-typescript-plugin/assets/95193764/c28eb6a9-077f-4c2b-ab20-9b34bb146394">
